# Generated by Django 2.2.2 on 2019-09-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20190905_1926'),
        ('teams', '0002_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='squad',
            field=models.ManyToManyField(related_name='squads', to='clubs.Member'),
        ),
    ]
