# Generated by Django 2.1.11 on 2019-09-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='squad',
            field=models.ManyToManyField(blank=True, related_name='squads', to='clubs.Member'),
        ),
    ]
