# Generated by Django 3.0.3 on 2020-10-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0053_auto_20200917_2329'),
        ('teams', '0004_auto_20190917_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='involved_in',
            field=models.ManyToManyField(blank=True, to='fixtures.Competition'),
        ),
    ]
