# Generated by Django 2.2.2 on 2019-08-21 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Venue'),
        ),
    ]
