# Generated by Django 2.2.2 on 2019-08-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('clubs', '0003_auto_20190822_1631'),
        ('fixtures', '0003_fixture_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='team_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_a_fixtures', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_b_fixtures', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='VenueUseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_type', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='FixtureCancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_cancelled', models.DateTimeField()),
                ('cancellation_reason', models.CharField(max_length=30)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Fixture')),
            ],
        ),
    ]
