# Generated by Django 2.2.2 on 2019-08-24 22:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0004_auto_20190822_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='competition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fixtures.Competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixture',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
