# Generated by Django 2.2.2 on 2019-08-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0005_auto_20190824_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='short_name',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
