# Generated by Django 2.2.2 on 2019-08-24 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0006_auto_20190824_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fixtures.Season'),
            preserve_default=False,
        ),
    ]
