# Generated by Django 2.2.2 on 2019-08-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_auto_20190824_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='display_name',
            field=models.CharField(default='', max_length=7),
            preserve_default=False,
        ),
    ]
