# Generated by Django 2.2.2 on 2019-08-24 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0008_season_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='parent_competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_competition', to='fixtures.Competition'),
        ),
    ]
