# Generated by Django 2.2.2 on 2019-08-24 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0010_auto_20190825_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Venue'),
        ),
    ]
