# Generated by Django 2.2.2 on 2019-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0011_auto_20190825_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='street_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
