# Generated by Django 2.2.2 on 2019-09-05 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixtures', '0012_venue_street_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('matchofficial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fixtures.MatchOfficial')),
            ],
            options={
                'abstract': False,
            },
            bases=('fixtures.matchofficial',),
        ),
        migrations.CreateModel(
            name='CompetitionOfficial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='officials',
            field=models.ManyToManyField(to='fixtures.CompetitionOfficial'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='umpire_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_umpire_a', to='fixtures.Umpire'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='umpire_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_umpire_b', to='fixtures.Umpire'),
        ),
    ]
