# Generated by Django 2.1.1 on 2019-09-07 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0013_auto_20190905_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('penalty', models.ManyToManyField(to='fixtures.Penalty')),
            ],
        ),
        migrations.CreateModel(
            name='RuleParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('rules', models.ManyToManyField(to='fixtures.Rule')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='rules',
            field=models.ManyToManyField(to='fixtures.RuleSet'),
        ),
    ]
