# Generated by Django 2.1.1 on 2019-09-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0014_auto_20190907_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'verbose_name_plural': 'penalties'},
        ),
        migrations.AlterField(
            model_name='rule',
            name='penalty',
            field=models.ManyToManyField(blank=True, null=True, to='fixtures.Penalty'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='rules',
            field=models.ManyToManyField(blank=True, null=True, to='fixtures.Rule'),
        ),
    ]
