# Generated by Django 2.1.1 on 2019-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0016_ruleset_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleparagraph',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='penalty',
            field=models.ManyToManyField(blank=True, to='fixtures.Penalty'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='competitions',
            field=models.ManyToManyField(blank=True, to='fixtures.Competition'),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='rules',
            field=models.ManyToManyField(blank=True, to='fixtures.Rule'),
        ),
    ]
