# Generated by Django 2.1.1 on 2019-09-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0017_auto_20190907_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruleset',
            name='competitions',
        ),
    ]
