# Generated by Django 2.1.1 on 2019-09-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0018_remove_ruleset_competitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='officials',
            field=models.ManyToManyField(blank=True, to='fixtures.CompetitionOfficial'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='rules',
            field=models.ManyToManyField(blank=True, to='fixtures.RuleSet'),
        ),
    ]
