# Generated by Django 2.1.1 on 2019-09-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0019_auto_20190907_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionofficial',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
