# Generated by Django 2.1.11 on 2019-09-11 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_clubmanagementposition_type'),
        ('fixtures', '0020_competitionofficial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturecancellation',
            name='cancellation_reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Member'),
        ),
        migrations.AddField(
            model_name='fixturecancellation',
            name='more_info',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
