# Generated by Django 2.1.11 on 2019-09-16 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0021_auto_20190911_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='umpire_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_umpire_a', to='fixtures.Umpire'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='umpire_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_as_umpire_b', to='fixtures.Umpire'),
        ),
    ]
