# Generated by Django 2.1.11 on 2019-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0022_auto_20190917_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='match_card_submission_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
