# Generated by Django 2.1.11 on 2019-09-30 16:00

from django.db import migrations, models
import django.db.models.deletion
import fixtures.utils.general


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0024_matchcardimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=20)),
                ('additional_comments', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('response_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.CompetitionOfficial')),
            ],
        ),
        migrations.AlterField(
            model_name='matchcardimage',
            name='image',
            field=models.FileField(unique=True, upload_to=fixtures.utils.general.get_file_path),
        ),
        migrations.AddField(
            model_name='fixturecancellation',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fixtures.CancellationResponse'),
        ),
    ]
