# Generated by Django 2.1.11 on 2019-10-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0026_auto_20191002_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturecancellation',
            name='cancelled_by_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team'),
        ),
    ]
