# Generated by Django 2.1.11 on 2019-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0027_auto_20191002_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcardimage',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
