# Generated by Django 2.1.11 on 2019-10-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0028_matchcardimage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='ruleparagraph',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='ruleset',
            options={'ordering': ['number']},
        ),
    ]
