# Generated by Django 2.1.11 on 2019-10-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0029_auto_20191025_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='umpire',
            name='identification_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
