# Generated by Django 2.1.11 on 2019-10-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20191030_2239'),
        ('fixtures', '0030_umpire_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchofficial',
            name='associated_club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Club'),
        ),
    ]
