# Generated by Django 2.1.11 on 2019-11-10 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20191030_2239'),
        ('fixtures', '0031_matchofficial_associated_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureRearrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=150)),
                ('_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rearrangement_from', to='fixtures.Fixture')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rearrangement_to', to='fixtures.Fixture')),
            ],
        ),
        migrations.CreateModel(
            name='RearrangementRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_date_time', models.DateTimeField()),
                ('date_time_created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=30)),
                ('original_fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Fixture')),
                ('who_requested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Member')),
            ],
        ),
    ]
