# Generated by Django 2.1.11 on 2019-11-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0033_rearrangementresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rearrangementresponse',
            old_name='_type',
            new_name='answer',
        ),
    ]
