# Generated by Django 2.1.11 on 2019-11-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0036_auto_20191117_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixturerearrangement',
            old_name='_from',
            new_name='from_fixture',
        ),
        migrations.RenameField(
            model_name='fixturerearrangement',
            old_name='to',
            new_name='to_fixture',
        ),
    ]
