# Generated by Django 2.1.11 on 2019-12-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0037_auto_20191117_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionConfigItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25)),
                ('value', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='config',
            field=models.ManyToManyField(blank=True, null=True, to='fixtures.CompetitionConfigItem'),
        ),
    ]
