# Generated by Django 2.1.11 on 2019-12-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0038_auto_20191214_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='config',
            field=models.ManyToManyField(blank=True, to='fixtures.CompetitionConfigItem'),
        ),
    ]
