# Generated by Django 2.1.11 on 2019-12-15 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixtures', '0039_auto_20191214_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturerearrangement',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
