# Generated by Django 2.1.11 on 2019-12-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_auto_20191217_2008'),
        ('teams', '0004_auto_20190917_0022'),
        ('fixtures', '0040_fixturerearrangement_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designated_captain', models.BooleanField()),
                ('designated_substitute', models.BooleanField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Fixture')),
            ],
        ),
        migrations.CreateModel(
            name='FixtureResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a_score', models.PositiveSmallIntegerField()),
                ('team_b_score', models.PositiveSmallIntegerField()),
                ('team_a_points', models.IntegerField()),
                ('team_b_points', models.IntegerField()),
                ('draw', models.BooleanField()),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losses', to='teams.Team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wins', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_played', models.PositiveIntegerField()),
                ('num_won', models.PositiveIntegerField()),
                ('num_lost', models.PositiveIntegerField()),
                ('num_drawn', models.PositiveIntegerField()),
                ('goal_difference', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Competition')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_occurred', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fixtures.MatchEvent')),
            ],
            bases=('fixtures.matchevent',),
        ),
        migrations.CreateModel(
            name='PersonalPenalty',
            fields=[
                ('matchevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fixtures.MatchEvent')),
                ('penalty_type', models.CharField(max_length=50)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Umpire')),
            ],
            bases=('fixtures.matchevent',),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.FixtureResult'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='player_involved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Player'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Player'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixtures.FixtureResult'),
        ),
    ]
