# Generated by Django 3.0.3 on 2020-05-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0041_auto_20191220_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='designated_captain',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='designated_substitute',
        ),
    ]
