# Generated by Django 3.0.3 on 2020-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0042_auto_20200530_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='squad_a_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='squad_b_selected',
            field=models.BooleanField(default=False),
        ),
    ]
