# Generated by Django 3.0.3 on 2020-06-08 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20190917_0022'),
        ('fixtures', '0043_auto_20200604_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fixtures.Competition'),
        ),
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
