# Generated by Django 3.0.3 on 2020-06-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0044_auto_20200608_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='player_involved',
        ),
        migrations.AddField(
            model_name='fixtureresult',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='appearance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fixtures.Appearance'),
        ),
        migrations.AlterField(
            model_name='fixtureresult',
            name='draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fixtureresult',
            name='team_a_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixtureresult',
            name='team_a_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixtureresult',
            name='team_b_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixtureresult',
            name='team_b_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
