# Generated by Django 3.0.3 on 2020-06-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0046_auto_20200620_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_card_image', models.ImageField(upload_to='')),
                ('squad_a_selected', models.BooleanField()),
                ('squad_b_selected', models.BooleanField()),
                ('scorers_submitted', models.BooleanField()),
                ('personal_penalties_submitted', models.BooleanField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='personalpenalty',
            options={'verbose_name_plural': 'Personal penalties'},
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='squad_a_selected',
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='squad_b_selected',
        ),
        migrations.AddField(
            model_name='fixture',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixtures.FixtureMetadata'),
        ),
    ]
