# Generated by Django 3.0.3 on 2020-08-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0048_auto_20200717_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturemetadata',
            name='time_match_card_complete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='time_match_card_image_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='time_penalties_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='time_scorers_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='time_squad_a_selected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='time_squad_b_selected',
            field=models.DateTimeField(null=True),
        ),
    ]
