# Generated by Django 3.0.3 on 2020-08-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0049_auto_20200822_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='current_season',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_current', to='fixtures.Season'),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='issue_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='start_time_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='time_start_time_submitted',
            field=models.DateTimeField(null=True),
        ),
    ]
