# Generated by Django 3.0.3 on 2020-09-17 19:09

from django.db import migrations, models
import fixtures.models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0051_fixturemetadata_match_card_image_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixturemetadata',
            name='match_card_image',
            field=models.ImageField(null=True, upload_to=fixtures.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='matchcardimage',
            name='image',
            field=models.FileField(unique=True, upload_to=fixtures.models.get_file_path),
        ),
    ]
