# Generated by Django 3.0.3 on 2020-09-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0052_auto_20200917_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixturemetadata',
            name='captain_a_signed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='captain_b_signed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='umpire_a_signed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fixturemetadata',
            name='umpire_b_signed',
            field=models.BooleanField(null=True),
        ),
    ]
