# Generated by Django 2.2.2 on 2019-08-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_competition'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueUseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_type', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixtures.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='venues',
            field=models.ManyToManyField(through='clubs.VenueUseType', to='fixtures.Venue'),
        ),
    ]
