# Generated by Django 2.2.2 on 2019-08-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_venues'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='short_name',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
