# Generated by Django 2.1.1 on 2019-09-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20190905_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubManagementPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Member')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='management',
            field=models.ManyToManyField(related_name='management_position', through='clubs.ClubManagementPosition', to='clubs.Member'),
        ),
    ]
