# Generated by Django 2.1.11 on 2019-09-12 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_clubmanagementposition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_submitted', models.DateTimeField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('evidence', models.FileField(upload_to='')),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Member')),
                ('transfer_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.Club')),
            ],
        ),
    ]
