# Generated by Django 2.1.11 on 2019-09-12 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_transferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrequest',
            name='transfer_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='clubs.Club'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='transfer_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='clubs.Club'),
        ),
    ]
