# Generated by Django 2.1.11 on 2019-09-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_auto_20190914_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
