# Generated by Django 2.1.11 on 2019-09-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_auto_20190917_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fixture_coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixture_coordinator_for', to='clubs.Member'),
        ),
        migrations.AddField(
            model_name='club',
            name='main_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_contact_for', to='clubs.Member'),
        ),
    ]
