# Generated by Django 2.1.11 on 2019-10-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_auto_20190930_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='dashboard_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
