# Generated by Django 2.1.11 on 2019-12-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_auto_20191030_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmanagementposition',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
