# Generated by Django 3.0.3 on 2020-07-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_auto_20191217_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
